name: Scheduled Python Script 1

on:
  push:  # Allows manual trigger of the workflow

permissions:
  contents: read

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon

    - name: Run script in loop
      run: |
        while true; do
          echo "Running z.py..."
          python3 z.py
          echo "Waiting for 60 seconds..."
          sleep 60
        done
